### ISSUE TITLE
Option to ignore DTD?

### ISSUE THREAD

**Issue by Awlexus** [kbrw/sweet_xml#104]
Is it possible to disable the validation of DTD? I do not need to the structure, but it has been declared in the input I'm unable to extract the data I need

**Comment by Shakadak** [comment]
Hello, can you provide an example where it didn't work ?
Have you tried with the option `dtd: :all` as described in [parse/2](https://hexdocs.pm/sweet_xml/SweetXml.html#parse/2) ?

**Comment by Awlexus** [comment]
Thank you for the fast reply. In my case, it is simply specified as `<!DOCTYPE type SYSTEM "type.dtd">`, which raises because I do not have the file on my system, causes the following error:

```
08:06:04.485 [error] Process #PID<0.1959.0> raised an exception
** (CaseClauseError) no case clause matching: {:error, :enoent}
    (xmerl 2.0) xmerl_scan.erl:1389: :xmerl_scan.fetch_DTD/2
    (xmerl 2.0) xmerl_scan.erl:1333: :xmerl_scan.scan_doctype2/3
    (xmerl 2.0) xmerl_scan.erl:859: :xmerl_scan.scan_prolog2/4
    (xmerl 2.0) xmerl_scan.erl:669: :xmerl_scan.scan_document/2
    (xmerl 2.0) xmerl_scan.erl:390: :xmerl_scan.string/2
```

I do know which file is referenced and have it downloaded, but the documentation for both SweetXML and xmerl are about where to save those files.

**Comment by Shakadak** [comment]
Okay, so I did a few tests based on [1.4 Fetch Function](https://www.erlang.org/doc/apps/xmerl/xmerl_examples.html)

If you want to ignore the DTD file, you have to provide a `fetch_fun` that will return `{:ok, :not_fetched, new_global_state}`, for example:
```elixir

    xml =
      ~S"""
      <!DOCTYPE type SYSTEM "type.dtd">
      <tag></tag>
      """

    _= SweetXml.parse(xml, dtd: :all, fetch_fun: fn uri, state ->
      _ = IO.inspect(uri, label: "fetch uri")
      {:ok, :not_fetched, state}
    end)
```

But if the definitions are needed and you have the file, like you said in your last comment, then it must be located in the same folder as where you are running your program. Here is an example reusing the tag you provided:
```elixir
    xml =
      ~S"""
      <!DOCTYPE type SYSTEM "type.dtd">
      <tag></tag>
      """

    _ = File.touch!("type.dtd")
    _= SweetXml.parse(xml, dtd: :all)
    _ = File.rm!("type.dtd")
  end
```
If you remove the `File.rm!`, you'll see that it was written locally. If you try to touch it somewhere else, it will fail.

**Comment by Shakadak** [comment]
I only saw after that you didn't know which file was referenced, you can use something like the following to determine it:
```elixir
    xml =
      ~S"""
      <!DOCTYPE type SYSTEM "type.dtd">
      <tag></tag>
      """

    _= SweetXml.parse(xml, dtd: :all, fetch_fun: fn uri, state ->
      case uri do
        {:system, path} ->
          _ = IO.inspect(path, label: "File to be fetched")
          {:ok, {:file, path}, state}

        other ->
          _ = IO.inspect(other, label: "Unhandled URI not fetched")
          {:ok, :not_fetched, state}
      end
    end)
```
I suppose it is linear and so the first fail will follow the last inspect that printed a file path, but to be certain, you can pattern match on `path` to eliminate the files you already have.
