### ISSUE TITLE
Memory leak in streaming support

### ISSUE THREAD

**Issue by ssbb** [kbrw/sweet_xml#38]
Just tried to parse 4GB file (http://www.litres.ru/static/ds/detailed_data.xml.gz) with `stream_tags` and got memory leaks until BEAM crashes.

My code example:

```
File.stream!("/home/ssbb/tmp/detailed_data.xml", [:utf8])
|> stream_tags(:art)
|> Stream.each(fn {tag, doc} ->
  IO.inspect DateTime.utc_now
end)
|> Stream.run
```

https://f001.backblazeb2.com/file/ssbb-me/1478737792.png

[crash_dump.zip](https://github.com/awetzel/sweet_xml/files/582266/crash_dump.zip)

**Comment by sweco-semtne** [comment]
I have the same problem unfortunately. Is this a known problem?

**Comment by alex88** [comment]
Same here, any clue?

**Comment by Thog** [comment]
As stated here https://github.com/kbrw/sweet_xml/blob/40e843c0560490c26a38a01c2c4f9eaefd53ba67/lib/sweet_xml.ex#L242-L244

```
  Most common usage of streaming: stream a given tag or a list of tags, and
  optionally "discard" some dom elements in order to free memory during streaming
  for big files which cannot fit entirely in memory.
```

You need to discard elements from the stream by using the 'option' parameter of stream_tags/2

**Comment by janajri** [comment]
I'm also having a similar issue here. I have a 300mb xml file that needs to be loaded into memory into it's entirety. Is there some tuning that can be done to handle this case? Would increasing the process heap size be the appropriate step?

**Comment by janajri** [comment]
I seem to be running into a similar issue attempting to parse a 500mb file with this: 
```
      File.stream!(file, [:read])
      |> SweetXml.stream_tags(tags, discard: @discard)
      |> Stream.run
``` 
My process memory balloons to 4-5Gb.
