### ISSUE TITLE
Please create releases for new versions

### ISSUE THREAD

**Issue by atonse** [kbrw/sweet_xml#40]
I recently installed sweet_xml and put in version 0.3.0 since that was what I found in the releases pages. After upgrading to elixir 1.4, I had a few issues – only after lots of troubleshooting in slack, I found that the latest version is actually 0.6.3.

Is it possible to create releases for each new version? Or is there a better way to know which is the latest version? (without looking at the mix.exs file – because that doesn't necessarily mean that's the latest version available)

**Comment by awetzel** [comment]
Hello Atonse, 
actually now the best way to install and follow version is to follow versions on hex.pm https://hex.pm/packages/sweet_xml
And install it with mix / hex

**Comment by atonse** [comment]
@awetzel sounds good – thanks. would it be useful to remove the existing releases from github to reinforce the point?

**Comment by atonse** [comment]
Also, thank you for this library. It's worked really well!
