### ISSUE TITLE
How to handle parsing errors?

### ISSUE THREAD

**Issue by GBH** [kbrw/sweet_xml#48]
Right now I have to do something like this (not sure if right):
```
defp parse_xml(doc) do
  try do
    points = xpath(doc, ~x"//trk/trkseg/trkpt"l, lat: ~x"./@lat"F, lng: ~x"./@lon"F, ele: ~x"./ele/text()"I)
    {:ok, points}
  catch
    :exit, _ -> {:error, "unable to parse .gpx file"}
  end
end
```
Why doesn't it follow something like this:
```
case xpath(doc, ~"whatever") do
  {:ok, result} -> do something
  {:error, message} -> do something else
end
```
While this works it still dumps error into stdout `20:34:30.188 [error] 3904- fatal: :expected_element_start_tag`. Kinda gross.

I'm kinda new to this whole elixir thing, maybe I'm doing something wrong? I looked into Task but it doesn't appear to solve this issue.

**Comment by chalmagean** [comment]
Did you figure this one out? I'm in the same boat, not sure how to best handle the failure and why there's that fatal error or where it comes from.

**Comment by GBH** [comment]
@chalmagean No, I'm still doing that `try` `catch` thing.

**Comment by seantanly** [comment]
@chalmagean @GBH 

Looks like it's not a runtime error, but error message spew out by xmerl which can be safely ignored, according to the following thread.

https://elixirforum.com/t/rescuing-from-an-erlang-error/1132

**Comment by 9mm** [comment]
Id also love to know how to prevent it from logging errors if its in a begin/catch block

**Comment by leather-s** [comment]
Can we please do something about the horrid error handling in this lib?

**Comment by Shakadak** [comment]
Hi all,

regarding the error handling, we will look at it at a later time, for now you will have to keep on using `catch`
as for the logging error, you can pass the option `quiet: true` as specified in the [xmerl_scan doc](https://erlang.org/doc/man/xmerl_scan.html#type-option_list) by splitting the operation in two:

```elixir
try do
  {:ok, SweetXml.xpath(SweetXml.parse(xml, quiet: true), spec)}
catch
  :exit, _ -> :error
end
```

**Comment by thbar** [comment]
Is it still planned at some point? It is very much catching users off-guard. Thanks!
