### ISSUE TITLE
"** (Mix) Could not start application sweet_xml: could not find application file: sweet_xml.app" error after 'uninstalling'

### ISSUE THREAD

**Issue by kenny-evitt** [kbrw/sweet_xml#78]
By "'uninstalling'", I mean that I installed `SweetXml`, but with one particular branch of my project's Git repo checked-out. I've switched to another second branch that does NOT include adding `SweetXml` but when I try to run my project via Mix (via `iex -S mix` specifically), I get this error:

```
** (Mix) Could not start application sweet_xml: could not find application file: sweet_xml.app
```

I tried `mix clean && mix deps.clean --unused && mix deps.get && mix compile` and the app compiles fine.

AFAICT, there are NO references to `SweetXml` in any Elixir files with the second branch checked-out.

I did finally try `mix deps.clean --all && mix deps.get` and that resolved the error, but that was *mildly* painful as it took a few minutes.

Any ideas on what might have persisted in my project's repo that caused the app to fail to start after 'uninstalling' `SweetXml`?

Some possibly relevant lines from my project's `.gitignore` file:

```
/_build
/deps
```

**Comment by Shakadak** [comment]
Hi, have you tried to replicate this issue with another dependency ? This looks more like an elixir/mix issue than something particular to sweet_xml. The only place you should find `x.app` is in `_build/{env}/lib/x/ebin/`

**Comment by kenny-evitt** [comment]
@Shakadak Thanks for following-up! I haven't tried replicating this. I'm not sure where to start. But I haven't run into this in a long while. I'm going to close this for now. If I run into it again, and have some time to look at it in more detail, I'll update this issue.
