### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by Blackstaff** [kbrw/sweet_xml#79]
Hello,
there have been no new commits since Feb 24, 2019 and some of the PRs (most importantly #53 and  #36) are left unresolved.
We (Kontomatik) would love to to take the maintenance of sweet_xml upon ourselves if you no longer have the time/need/want to do it.

**Comment by Oxydros** [comment]
Hi Blackstaff,

Our Github wasn't really maintained this past few years, but we are planning on changing that.

We will review everything in April, and maybe open the repository to outside contributors. I will be sure to come back to you if this is the case :)

**Comment by Blackstaff** [comment]
Hi Oxydros,
thank you for the info :smiley:

**Comment by Blackstaff** [comment]
BTW we've created a fork (https://github.com/kontomatik/sweet_xml) - not much has been done yet (just 2 PR merges).

**Comment by MordecaiMalignatus** [comment]
Thanks for the fork! We just ran into this and switched to the fork for the time being.

**Comment by osazemeu** [comment]
Is this package still maintained? I don't mind taking it up.
sweet_xml 0.7.5 emits an Elixir 1.19 typing violation at lib/sweet_xml.ex:246 (struct update on an un-pattern-matched xpath).
